"use client";
import "./globals.css";
import { Poppins } from "next/font/google";
import { AuthContextProvider } from "./context/AuthContext";
import { NavBar } from "./components/NavBar";

const poppins = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });


// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html data-theme="winter">
      <body className={`${poppins.className} min-h-screen`}>
        <AuthContextProvider>
          {/* <NavBar /> */}
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}